name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: debian-bookworm

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Clone Zeal-8-bit-OS repository
      run: git clone https://github.com/Zeal8bit/Zeal-8-bit-OS.git

    - name: Set ZOS_PATH environment variable
      run: echo "ZOS_PATH=$(pwd)/Zeal-8-bit-OS" >> $GITHUB_ENV

    - name: Update apt
      run: sudo apt update

    - name: Install sdcc
      run: sudo apt install sdcc=4.3.0

    - name: Run make
      run: make
